version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_MODEL=llama3.2
    volumes:
      - ./backend/data:/app/data
      - ./backend/.env:/app/.env
    depends_on:
      - ollama
    networks:
      - dia-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dia-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - dia-network

  slack-bot:
    build:
      context: ./slack-bot
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=http://backend:8000
    env_file:
      - ./slack-bot/.env
    depends_on:
      - backend
    networks:
      - dia-network
    profiles:
      - slack

volumes:
  ollama_data:

networks:
  dia-network:
    driver: bridge